package pk.ma.amitie.models;
// Generated 22 mars 2022 18:34:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Albums generated by hbm2java
 */
@Entity
@Table(name="ALBUMS"
    ,schema="AMITIE"
)
public class Albums  implements java.io.Serializable {


     private long idal;
     private Utilisateur utilisateur;
     private String name;
     private Set<Image> images = new HashSet<Image>(0);

    public Albums() {
    }

	
    public Albums(long idal) {
        this.idal = idal;
    }
    public Albums(long idal, Utilisateur utilisateur, String name, Set<Image> images) {
       this.idal = idal;
       this.utilisateur = utilisateur;
       this.name = name;
       this.images = images;
    }
   
     @Id 

    
    @Column(name="IDAL", unique=true, nullable=false, precision=10, scale=0)
    public long getIdal() {
        return this.idal;
    }
    
    public void setIdal(long idal) {
        this.idal = idal;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDU")
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="NAME", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="albums")
    public Set<Image> getImages() {
        return this.images;
    }
    
    public void setImages(Set<Image> images) {
        this.images = images;
    }




}


