package pk.ma.amitie.models;
// Generated 22 mars 2022 18:34:50 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Amis generated by hbm2java
 */
@Entity
@Table(name="AMIS"
    ,schema="AMITIE"
)
@SequenceGenerator(name = "seq_amis",sequenceName = "seq_amis")
public class Amis  implements java.io.Serializable {


     private int id;
     private Utilisateur utilisateurByIdu;
     private Utilisateur utilisateurByIduAmis;
     
     private Date dateamitie;

    public Amis() {
    }

	
    public Amis(int id) {
        this.id = id;
    }
    public Amis(int id, Utilisateur utilisateurByIdu,Utilisateur utilisateurByIduAmis,  Date dateamitie) {
       this.id = id;
       this.utilisateurByIduAmis = utilisateurByIduAmis;
       this.utilisateurByIdu = utilisateurByIdu;
       this.dateamitie = dateamitie;
    }
   
     @Id 

     @GeneratedValue(generator = "seq_amis",strategy = GenerationType.SEQUENCE)
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDU_AMIS")
    public Utilisateur getUtilisateurByIduAmis() {
        return this.utilisateurByIduAmis;
    }
    
    public void setUtilisateurByIduAmis(Utilisateur utilisateurByIduAmis) {
        this.utilisateurByIduAmis = utilisateurByIduAmis;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDU")
    public Utilisateur getUtilisateurByIdu() {
        return this.utilisateurByIdu;
    }
    
    public void setUtilisateurByIdu(Utilisateur utilisateurByIdu) {
        this.utilisateurByIdu = utilisateurByIdu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEAMITIE", length=7)
    public Date getDateamitie() {
        return this.dateamitie;
    }
    
    public void setDateamitie(Date dateamitie) {
        this.dateamitie = dateamitie;
    }




}


