package pk.ma.amitie.models;
// Generated 22 mars 2022 18:34:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Commentaire generated by hbm2java
 */
@Entity
@Table(name="COMMENTAIRE"
    ,schema="AMITIE"
)
public class Commentaire  implements java.io.Serializable {


     private long idc;
     private Utilisateur utilisateur;
     private Posts posts;
     private String contenu;

    public Commentaire() {
    }

	
    public Commentaire(long idc) {
        this.idc = idc;
    }
    public Commentaire(long idc, Utilisateur utilisateur, Posts posts, String contenu) {
       this.idc = idc;
       this.utilisateur = utilisateur;
       this.posts = posts;
       this.contenu = contenu;
    }
   
     @Id 

    
    @Column(name="IDC", unique=true, nullable=false, precision=10, scale=0)
    public long getIdc() {
        return this.idc;
    }
    
    public void setIdc(long idc) {
        this.idc = idc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDU")
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="POST_ID")
    public Posts getPosts() {
        return this.posts;
    }
    
    public void setPosts(Posts posts) {
        this.posts = posts;
    }

    
    @Column(name="CONTENU", length=1000)
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }




}


