package pk.ma.amitie.models;
// Generated 22 mars 2022 18:34:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Groupe generated by hbm2java
 */
@Entity
@Table(name="GROUPE"
    ,schema="AMITIE"
)
public class Groupe  implements java.io.Serializable {


     private long idg;
     private Utilisateur utilisateur;
     private String name;

    public Groupe() {
    }

	
    public Groupe(long idg) {
        this.idg = idg;
    }
    public Groupe(long idg, Utilisateur utilisateur, String name) {
       this.idg = idg;
       this.utilisateur = utilisateur;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="IDG", unique=true, nullable=false, precision=10, scale=0)
    public long getIdg() {
        return this.idg;
    }
    
    public void setIdg(long idg) {
        this.idg = idg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDU")
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="NAME", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


