package pk.ma.amitie.models;
// Generated 22 mars 2022 18:34:50 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Image generated by hbm2java
 */
@Entity
@Table(name="IMAGE"
    ,schema="AMITIE"
)
public class Image  implements java.io.Serializable {


     private long id;
     private Albums albums;
     private String path;
     private String name;

    public Image() {
    }

	
    public Image(long id) {
        this.id = id;
    }
    public Image(long id, Albums albums, String path, String name) {
       this.id = id;
       this.albums = albums;
       this.path = path;
       this.name = name;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=10, scale=0)
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ALBUM_ID")
    public Albums getAlbums() {
        return this.albums;
    }
    
    public void setAlbums(Albums albums) {
        this.albums = albums;
    }

    
    @Column(name="PATH", length=50)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    
    @Column(name="NAME", length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


