package pk.ma.amitie.models;
// Generated 22 mars 2022 18:34:50 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Partage generated by hbm2java
 */
@Entity
@Table(name="PARTAGE"
    ,schema="AMITIE"
)
public class Partage  implements java.io.Serializable {


     private long idp;
     private Utilisateur utilisateurByIdu;
     private Utilisateur utilisateurByIduPartage;
     private Posts posts;
     private Date datepartage;

    public Partage() {
    }

	
    public Partage(long idp) {
        this.idp = idp;
    }
    public Partage(long idp, Utilisateur utilisateurByIdu, Utilisateur utilisateurByIduPartage, Posts posts, Date datepartage) {
       this.idp = idp;
       this.utilisateurByIdu = utilisateurByIdu;
       this.utilisateurByIduPartage = utilisateurByIduPartage;
       this.posts = posts;
       this.datepartage = datepartage;
    }
   
     @Id 

    
    @Column(name="IDP", unique=true, nullable=false, precision=10, scale=0)
    public long getIdp() {
        return this.idp;
    }
    
    public void setIdp(long idp) {
        this.idp = idp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDU")
    public Utilisateur getUtilisateurByIdu() {
        return this.utilisateurByIdu;
    }
    
    public void setUtilisateurByIdu(Utilisateur utilisateurByIdu) {
        this.utilisateurByIdu = utilisateurByIdu;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDU_PARTAGE")
    public Utilisateur getUtilisateurByIduPartage() {
        return this.utilisateurByIduPartage;
    }
    
    public void setUtilisateurByIduPartage(Utilisateur utilisateurByIduPartage) {
        this.utilisateurByIduPartage = utilisateurByIduPartage;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="POST_ID")
    public Posts getPosts() {
        return this.posts;
    }
    
    public void setPosts(Posts posts) {
        this.posts = posts;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEPARTAGE", length=7)
    public Date getDatepartage() {
        return this.datepartage;
    }
    
    public void setDatepartage(Date datepartage) {
        this.datepartage = datepartage;
    }




}


