package pk.ma.amitie.models;
// Generated 22 mars 2022 18:34:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pays generated by hbm2java
 */
@Entity
@Table(name="PAYS"
    ,schema="AMITIE"
)
public class Pays  implements java.io.Serializable {


     private int idp;
     private String nomp;
     private Set<Ville> villes = new HashSet<Ville>(0);

    public Pays() {
    }

	
    public Pays(int idp) {
        this.idp = idp;
    }
    public Pays(int idp, String nomp, Set<Ville> villes) {
       this.idp = idp;
       this.nomp = nomp;
       this.villes = villes;
    }
   
     @Id 

    
    @Column(name="IDP", unique=true, nullable=false, precision=8, scale=0)
    public int getIdp() {
        return this.idp;
    }
    
    public void setIdp(int idp) {
        this.idp = idp;
    }

    
    @Column(name="NOMP", length=30)
    public String getNomp() {
        return this.nomp;
    }
    
    public void setNomp(String nomp) {
        this.nomp = nomp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pays")
    public Set<Ville> getVilles() {
        return this.villes;
    }
    
    public void setVilles(Set<Ville> villes) {
        this.villes = villes;
    }




}


