package pk.ma.amitie.models;
// Generated 22 mars 2022 18:34:50 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Posts generated by hbm2java
 */
@Entity
@Table(name="POSTS"
    ,schema="AMITIE"
)
@SequenceGenerator(name = "seq_post",sequenceName = "seq_post")
public class Posts  implements java.io.Serializable {


     private int idp;
     private Utilisateur utilisateur;
     private String title;
     private String contenu;
     private Date dateposte;
     private String typeposte;
     private Long state;
     private Integer nbrlikes;
     private Integer nbrdeslikes;
     private Set<Likes> likeses = new HashSet<Likes>(0);
     private Set<Partage> partages = new HashSet<Partage>(0);
     
     private Set<Commentaire> commentaires = new HashSet<Commentaire>(0);

    public Posts() {
    }

	
    public Posts(int idp) {
        this.idp = idp;
    }
    public Posts(int idp, Utilisateur utilisateur, String title, String contenu, Date dateposte, String typeposte, Long state, Integer nbrlikes, Integer nbrdeslikes,  Set<Likes> likeses,Set<Partage> partages, Set<Commentaire> commentaires) {
       this.idp = idp;
       this.utilisateur = utilisateur;
       this.title = title;
       this.contenu = contenu;
       this.dateposte = dateposte;
       this.typeposte = typeposte;
       this.state = state;
       this.nbrlikes = nbrlikes;
       this.nbrdeslikes = nbrdeslikes;
      
       this.likeses = likeses;
        this.partages = partages;
       this.commentaires = commentaires;
    }
   
     @Id 

    @GeneratedValue(generator = "seq_post",strategy = GenerationType.SEQUENCE)
    @Column(name="IDP", unique=true, nullable=false, precision=10, scale=0)
    public int getIdp() {
        return this.idp;
    }
    
    public void setIdp(int idp) {
        this.idp = idp;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDU")
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="TITLE", length=150)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="CONTENU", length=1000)
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATEPOSTE", length=7)
    public Date getDateposte() {
        return this.dateposte;
    }
    
    public void setDateposte(Date dateposte) {
        this.dateposte = dateposte;
    }

    
    @Column(name="TYPEPOSTE", length=30)
    public String getTypeposte() {
        return this.typeposte;
    }
    
    public void setTypeposte(String typeposte) {
        this.typeposte = typeposte;
    }

    
    @Column(name="STATE", precision=10, scale=0)
    public Long getState() {
        return this.state;
    }
    
    public void setState(Long state) {
        this.state = state;
    }

    
    @Column(name="NBRLIKES", precision=8, scale=0)
    public Integer getNbrlikes() {
        return this.nbrlikes;
    }
    
    public void setNbrlikes(Integer nbrlikes) {
        this.nbrlikes = nbrlikes;
    }

    
    @Column(name="NBRDESLIKES", precision=8, scale=0)
    public Integer getNbrdeslikes() {
        return this.nbrdeslikes;
    }
    
    public void setNbrdeslikes(Integer nbrdeslikes) {
        this.nbrdeslikes = nbrdeslikes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="posts")
    public Set<Partage> getPartages() {
        return this.partages;
    }
    
    public void setPartages(Set<Partage> partages) {
        this.partages = partages;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="posts")
    public Set<Likes> getLikeses() {
        return this.likeses;
    }
    
    public void setLikeses(Set<Likes> likeses) {
        this.likeses = likeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="posts")
    public Set<Commentaire> getCommentaires() {
        return this.commentaires;
    }
    
    public void setCommentaires(Set<Commentaire> commentaires) {
        this.commentaires = commentaires;
    }




}


