package pk.ma.amitie.models;
// Generated 22 mars 2022 18:34:50 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ville generated by hbm2java
 */
@Entity
@Table(name="VILLE"
    ,schema="AMITIE"
)
public class Ville  implements java.io.Serializable {


     private int idv;
     private Pays pays;
     private String nomv;
     private Set<Utilisateur> utilisateurs = new HashSet<Utilisateur>(0);

    public Ville() {
    }

	
    public Ville(int idv) {
        this.idv = idv;
    }
    public Ville(int idv, Pays pays, String nomv, Set<Utilisateur> utilisateurs) {
       this.idv = idv;
       this.pays = pays;
       this.nomv = nomv;
       this.utilisateurs = utilisateurs;
    }
   
     @Id 

    
    @Column(name="IDV", unique=true, nullable=false, precision=8, scale=0)
    public int getIdv() {
        return this.idv;
    }
    
    public void setIdv(int idv) {
        this.idv = idv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="IDP")
    public Pays getPays() {
        return this.pays;
    }
    
    public void setPays(Pays pays) {
        this.pays = pays;
    }

    
    @Column(name="NOMV", length=30)
    public String getNomv() {
        return this.nomv;
    }
    
    public void setNomv(String nomv) {
        this.nomv = nomv;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ville")
    public Set<Utilisateur> getUtilisateurs() {
        return this.utilisateurs;
    }
    
    public void setUtilisateurs(Set<Utilisateur> utilisateurs) {
        this.utilisateurs = utilisateurs;
    }




}


